---
title: "bivariate relationships"
author: "Prabidhik KC"
date: "2022-10-22"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Loading necessary libraries

library(tidyverse)
library(gov50data)

covid_votes <- read_csv("covid_votes.csv")

covid_votes

```
```{r}
covid_votes %>% 
  mutate(
    one_dose_5p_centered = one_dose_5plus_pct - mean(one_dose_5plus_pct, na.rm = TRUE),
    one_dose_5p_z = one_dose_5p_centered/sd(one_dose_5plus_pct, na.rm = TRUE)
  ) %>% 
  filter(one_dose_5p_z < 2)
```

## Correlation

```{r}
cor(covid_votes$one_dose_5plus_pct, covid_votes$dem_pct_2020,
    use = "pairwise")
```
```{r}
covid_votes %>% 
  ggplot(mapping = aes(x = dem_pct_2020, y = one_dose_5plus_pct)) +
  geom_point(alpha = 0.5)
```

```{r}

covid_votes %>% 
  ggplot(mapping = aes(x = dem_pct_2000, y = one_dose_5plus_pct)) +
  geom_point(alpha = 0.5)
```
```{r}
cor(covid_votes$one_dose_5plus_pct, covid_votes$dem_pct_2000,
    use = "pairwise")
```

## Writing Functions
```{r}
z_score <- function(x) {
  (x - mean(x, na.rm = TRUE))/sd(x, na.rm = TRUE)
}

z_score(c(1, 2, 3, 4, 5))
```

```{r}
covid_votes %>% 
  mutate(
    one_dose_5p_z = z_score(one_dose_5plus_pct),
    one_dose_65p_z = z_score(one_dose_65plus_pct)
  )

## Finding the z scores for all the variables from start to end
covid_votes %>% 
  mutate(
    across(one_dose_5plus_pct:dem_pct_2020, z_score)
  )
```



